swagger: "2.0"
info:
  version: "0.0.1"
  title: REST In Ease
# during dev, should point to your local machine
host: 127.0.0.1:10011
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /user/list:
    x-swagger-router-controller: User
    get:
      description: All User List
      operationId: GetAllUsers
#      parameters:
#        - name: name
#          in: query
#          description: The name of the person to whom to say hello
#          type: string
#
#        - name: last_name
#          in: query
#          description: The name of the person to whom to say hello
#          type: string
      tags:
        - USER
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/StatusResponse"


  /auth/user/create:
    x-swagger-router-controller: Auth
    post:
      description: Auth User Registration
      operationId: AuthUserRegistration
      parameters:
        - name: AuthUserRegistration
          description: Auth User Registration Parameters
          in: body
          required: true
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First Name
              last_name:
                type: string
                description: Last Name
              email:
                type: string
                description: Email
              password:
                type: string
                description: Password
              phone_number:
                type: string
                description: Phone Number
              image:
                type: string
                description: Image
      tags:
        - AUTH
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/StatusResponse"


  /swagger:
    x-swagger-pipe: swagger_raw


# complex objects have schema definitions
definitions:

  StatusResponse:
    required:
      - status
    properties:
      status:
        type: object
        properties:
          statusCode:
            type: string
            description: 200 for success else error
          message:
            type: string
            description: success or error message
