module.exports = {
    SALT_ROUND: 10,
    SECRET: process.env.SECRET,
    DB_TYPE: {
        CHAR            : 'char',
        STRING          : 'string',
        TEXT            : 'text',
        SMALLINT        : 'smallint',
        BIGINT          : 'bigint',
        INTEGER         : 'int',
        SMALL_INTEGER   : 'smallint',
        BIG_INTEGER     : 'bigint',
        REAL            : 'real',
        DATE            : 'date',
        DATE_TIME       : 'datetime',
        TIME            : 'time',
        BLOB            : 'blob',
        TIMESTAMP       : 'timestamp',
        BINARY          : 'binary',
        BOOLEAN         : 'boolean',
        DECIMAL         : 'decimal',
        FLOAT           : 'float',
    },
    DB_TABLES: {
        USER                                : 'users',
    },
};
