module.exports = {
    APP_NAME: 'REST In Ease',
    APP_VERSION: '1.0.0',
    APP_DESCRIPTION: '',
    BASE_URL: process.env.BASE_URL,
    BASE_PATH: process.env.BASE_PATH,
    AUTH_SECRET: process.env.AUTH_SECRET,
    SALT_ROUND: 10,
    PUSH_QUEUE: {
        TEST_PUSH: 'TEST_PUSH',
    },
    MAIL_QUEUE: {},
    DB_TYPE: {
        CHAR            : 'char',
        STRING          : 'string',
        TEXT            : 'text',
        SMALLINT        : 'smallint',
        BIGINT          : 'bigint',
        INTEGER         : 'int',
        SMALL_INTEGER   : 'smallint',
        BIG_INTEGER     : 'bigint',
        REAL            : 'real',
        DATE            : 'date',
        DATE_TIME       : 'datetime',
        TIME            : 'time',
        BLOB            : 'blob',
        TIMESTAMP       : 'timestamp',
        BINARY          : 'binary',
        BOOLEAN         : 'boolean',
        DECIMAL         : 'decimal',
        FLOAT           : 'float',
    },
    DB_TABLES: {
        USER                                : 'users',
    },
};
